JTwitter/grails-app/domain/com/jmanne/user/Role.groovy
package com.jmanne.user

import com.jmanne.common.domain.BaseEntity

class Role extends BaseEntity{

	String authority

	static mapping = {
		cache true
	}

	static constraints = {
		authority blank: false, unique: true
	}
}

JTwitter/grails-app/domain/com/jmanne/user/User.groovy
package com.jmanne.user

import com.jmanne.common.domain.BaseEntity;

class User extends BaseEntity {
	
	def slugGeneratorService;

	String displayName
	String email
	String password
	String slug;
	boolean enabled = true
	boolean accountExpired
	boolean accountLocked
	boolean passwordExpired

	static constraints = {
		displayName blank: false, size: 5..25
		email blank: false, unique: true, email: true
		password blank: false
	}

	static mapping = {
		password column: '`password`'
	}

	Set<Role> getAuthorities() {
		UserRole.findAllByUser(this).collect { it.role } as Set
	}

	def beforeInsert() {
		encodePassword()
		this.slug = slugGeneratorService.generateSlug(this.class, "slug", displayName)
	}

	def beforeUpdate() {
		if (isDirty('password')) {
			encodePassword()
		}
		if (isDirty('displayName')) {
			this.slug = slugGeneratorService.generateSlug(this.class, "slug", displayName)
		}
	}

	protected void encodePassword() {
		password = springSecurityService.encodePassword(password)
	}
}

JTwitter/grails-app/domain/com/jmanne/user/UserRole.groovy
package com.jmanne.user

import org.apache.commons.lang.builder.HashCodeBuilder

import com.jmanne.common.domain.BaseEntity;

class UserRole extends BaseEntity implements Serializable {

	User user
	Role role

	boolean equals(other) {
		if (!(other instanceof UserRole)) {
			return false
		}

		other.user?.id == user?.id &&
			other.role?.id == role?.id
	}

	int hashCode() {
		def builder = new HashCodeBuilder()
		if (user) builder.append(user.id)
		if (role) builder.append(role.id)
		builder.toHashCode()
	}

	static UserRole get(long userId, long roleId) {
		find 'from UserRole where user.id=:userId and role.id=:roleId',
			[userId: userId, roleId: roleId]
	}

	static UserRole create(User user, Role role, boolean flush = false) {
		new UserRole(user: user, role: role).save(flush: flush, insert: true)
	}

	static boolean remove(User user, Role role, boolean flush = false) {
		UserRole instance = UserRole.findByUserAndRole(user, role)
		if (!instance) {
			return false
		}

		instance.delete(flush: flush)
		true
	}

	static void removeAll(User user) {
		executeUpdate 'DELETE FROM UserRole WHERE user=:user', [user: user]
	}

	static void removeAll(Role role) {
		executeUpdate 'DELETE FROM UserRole WHERE role=:role', [role: role]
	}

	static mapping = {
		id composite: ['role', 'user']
		version false
	}
}

JTwitter/grails-app/controllers/com/jmanne/user/UserController.groovy
package com.jmanne.user

import org.codehaus.groovy.grails.plugins.springsecurity.SpringSecurityUtils

import com.jmanne.twitter.Tweet

class UserController {

	def userService;
	
	def twitterService;
	
    def signup() {
        def user = new User();
		render view: "signup", model : [user : user]
    }

    def register() {
        def user = new User(params)
		if(!user.validate()) {
			render view: "signup", model : [user : user]
		} else {
			userService.save(user)
			flash.message = message(code: 'signup.success')
			redirect(controller : "login", action: "index")
		}
    }
	
	def tweets() {
		def tweet = new Tweet(params)
		def user = userService.getBySlug(params.id)
		def tweets = twitterService.findByUserId(user.id);
		def config = SpringSecurityUtils.securityConfig
		String postUrl = "${request.contextPath}${config.apf.filterProcessesUrl}"
		render view : "/twitter/home" , model: [tweet:tweet, tweets:tweets, user:user,postUrl: postUrl,
		                           rememberMeParameter: config.rememberMe.parameter];
	}
}

JTwitter/grails-app/views/user/_form.gsp
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span12">
		  <div class="control-group">
		  	<g:hasErrors bean="${user}" field="displayName">
		  		<span class="error"><g:message code="${user.errors.getFieldError("displayName").code}"/></span>
			</g:hasErrors>
		    <div class="controls">
		      <g:textField name="displayName" value="${user.displayName}" placeholder="Full name" class="span12"/>
		    </div>
		  </div>
		  <div class="control-group">
		  	<g:hasErrors bean="${user}" field="email">
		  		<span class="error"><g:message code="${user.errors.getFieldError("email").code}"/></span>
			</g:hasErrors>
		    <div class="controls">
		      <g:textField name="email" value="${user.email}" placeholder="Email" class="span12"/>
		    </div>
		  </div>
		  <div class="control-group">
		  	<g:hasErrors bean="${user}" field="password">
		  		<span class="error"><g:message code="${user.errors.getFieldError("password").code}"/></span>
		  	</g:hasErrors>
		    <div class="controls">
		      <g:passwordField name="password" value="${user.password}" placeholder="Password" class="span12"/>
		    </div>
		  </div>
		  <div class="control-group">
		    <div class="controls">
				<g:submitButton value="Sign up" name="signup" class="btn btn-info" id="register-btn" />		    
			</div>
		  </div>
		 <div class="control-group">
		    <div class="controls">
				Already have an account? 
				<g:link controller="login" action="auth">sign in here</g:link>
			</div>
		  </div>
    </div>
  </div>
</div>

JTwitter/grails-app/views/user/edit.gsp
<%@ page import="com.jmanne.user.User" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-user" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="signup"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-user" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${userInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${userInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form method="post" >
				<g:hiddenField name="id" value="${userInstance?.id}" />
				<g:hiddenField name="version" value="${userInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" formnovalidate="" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

JTwitter/grails-app/views/user/signup.gsp
<meta name='layout' content='main'/>
<div id='hbox'>
	<div class='inner'>
		<h3 class="header">Register</h3>
		<g:form controller="user" action="register" name="signupForm" class='cssform' autocomplete='off'>
			<g:render template="/user/form"/>
		</g:form>
    </div>
</div>